### ISSUE TITLE
kubectl get nodes will get "The connection to the server localhost:8080 was refused - did you specify the right host or port?" ERROR

### ISSUE THREAD

**Issue by YikaiHu** [aws-samples/eks-workshop#1306]
Hi all,
When I finished deploy the eks by following the guide.
I tried to check the eks clusters by `kubectl get nodes`
Then I got the error:
```
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

Here is my eksworkshop.yaml
```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: us-west-2
  version: "1.19"

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: m5.large
  ssh:
    enableSsm: true

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:us-west-2:12345678901:key/891999ea-7eef-4724-b3fd-011466c2d39f
```
I changed the instance type to m5.large, because there are no enough t3.small.
Thanks a lot!
