### ISSUE TITLE
StatefulSets: `init-mysql` `initContainer` fails because of missing `hostname` binary

### ISSUE THREAD

**Issue by iamsouravin** [aws-samples/eks-workshop#1479]
**Issue:**
The [Create StatefulSet](https://www.eksworkshop.com/beginner/170_statefulset/statefulset/) section fails to deploy the `mysql` workload because of missing `hostname` binary referred in the `initContainer` `command` script.

[mysql-statefulset.yaml](https://eksworkshop.com/beginner/170_statefulset/statefulset.files/mysql-statefulset.yaml) snippet

```yaml
initContainers:
- name: init-mysql
  image: mysql:5.7
  command:
  - bash
  - "-c"
  - |
    set -ex
    # Generate mysql server-id from pod ordinal index.
    [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
    ordinal=${BASH_REMATCH[1]}
    echo [mysqld] > /mnt/conf.d/server-id.cnf
    # Add an offset to avoid reserved server-id=0 value.
    echo server-id=$((100 + $ordinal)) >> /mnt/conf.d/server-id.cnf
    # Copy appropriate conf.d files from config-map to emptyDir.
    if [[ $ordinal -eq 0 ]]; then
      cp /mnt/config-map/master.cnf /mnt/conf.d/
    else
      cp /mnt/config-map/slave.cnf /mnt/conf.d/
    fi
```

**Steps to reproduce:**
Run through the section [Stateful containers using StatefulSets](https://www.eksworkshop.com/beginner/170_statefulset/) until you have reached [Watch StatefulSet](https://www.eksworkshop.com/beginner/170_statefulset/statefulset/#watch-statefulset) sub section.

The `rollout` gets stuck waiting for the pods to be ready.
```console
TeamRole:~/environment/ebs_statefulset $ kubectl apply -f ${HOME}/environment/ebs_statefulset/mysql-statefulset.yaml
statefulset.apps/mysql created
TeamRole:~/environment/ebs_statefulset $ kubectl -n mysql rollout status statefulset mysql
Waiting for 2 pods to be ready...

```

The `pod` `mysql-0` stays in crash loop and never recovers.
```console
TeamRole:~/environment $ kubectl -n mysql get pods -l app=mysql --watch
NAME      READY   STATUS       RESTARTS   AGE
mysql-0   0/2     Init:Error   2          28s
mysql-0   0/2     Init:CrashLoopBackOff   2          40s
mysql-0   0/2     Init:Error              3          51s
^C
```

The log from `init-mysql` container shows the error in the command execution.
```console
TeamRole:~/environment $ kubectl logs mysql-0 -n mysql -c init-mysql
++ hostname
bash: line 2: hostname: command not found
+ [[ '' =~ -([0-9]+)$ ]]
+ exit 1
```

**Fix:**
Patching the `command` script and replacing `hostname` with `uname -n` fixes the error.

```console
TeamRole:~/environment/ebs_statefulset $ diff mysql-statefulset.yaml mysql-statefulset_changed.yaml
26c26
<           [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
---
>           [[ `uname -n` =~ -([0-9]+)$ ]] || exit 1
```
