### ISSUE TITLE
Cluster setup for kubeflow tests is too complicated

### ISSUE THREAD

**Issue by Jeffwan** [aws-samples/eks-workshop#474]
https://eksworkshop.com/eksctl/launcheks/

Lots of users complain that this is complicated

1. If will get more AWS_AZS and come of the AZ may not have GPU instances
2. Lots of users don't have GPU instance
3. Some user does have GPU instance but only 1. By default, it asks 2 and lead command fail.

Can we have some simpler version. Just ask user copy and past following. 

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksworkshop
  region: us-west-2
  version: '1.13'
# If your region has multiple availability zones, you can specify 3 of them.
availabilityZones: ["us-west-2b", "us-west-2c", "us-west-2d"]

# NodeGroup holds all configuration attributes that are specific to a nodegroup
# You can have several node groups in your cluster.
nodeGroups:
  - name: cpu
    instanceType: m5.xlarge
    desiredCapacity: 2
    minSize: 0
    maxSize: 2
    volumeSize: 30
    ssh:
      allow: true
      publicKeyPath: '~/.ssh/id_rsa.pub'

  # Example of GPU node group - we set desired capacity to 0.
  - name: gpu
    instanceType: p3.8xlarge
    availabilityZones: ["us-west-2b"]
    desiredCapacity: 0
    minSize: 0
    maxSize: 4
    volumeSize: 50
    ssh:
      allow: true
      publicKeyPath: '~/.ssh/id_rsa.pub'
    labels:
      'k8s.amazonaws.com/accelerator': 'nvidia-tesla-v100'
```

**Comment by Jeffwan** [comment]
@dalbhanj @arun-gupta

**Comment by arun-gupta** [comment]
@Jeffwan We should absolutely simplify the workshop instructions. can you confirm that the entire workshop will work on CPU-based clusters?

**Comment by Jeffwan** [comment]
@arun-gupta It's working on CPU-based clusters. Only one experiment (MPI) uses GPU. We can ask users to skip this one.

**Comment by arun-gupta** [comment]
Thanks @dalbhanj, looking forward to review the PR

**Comment by arun-gupta** [comment]
@Jeffwan I'm thinking the following simplified eksctl config file:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksworkshop-eksctl
  region: us-west-2
  version: '1.13'
# If your region has multiple availability zones, you can specify 3 of them.
availabilityZones: ["us-west-2b", "us-west-2c", "us-west-2d"]

# NodeGroup holds all configuration attributes that are specific to a nodegroup
# You can have several node groups in your cluster.
nodeGroups:
  - name: cpu
    instanceType: m5.xlarge
    desiredCapacity: 2
    minSize: 0
    maxSize: 2
    volumeSize: 30

  # Example of GPU node group - we set desired capacity to 0.
  - name: gpu
    instanceType: p3.8xlarge
    availabilityZones: ["us-west-2b"]
    desiredCapacity: 0
    minSize: 0
    maxSize: 2
    volumeSize: 50
    labels:
      'k8s.amazonaws.com/accelerator': 'nvidia-tesla-v100'
```

Basically, changed the cluster name to match rest of the workshop, removed `ssh`, and changed max number of GPU instances from `'4' to `2`.

What do you think?
