### ISSUE TITLE
EFK fluentd daemonset issue

### ISSUE THREAD

**Issue by blackdog0403** [aws-samples/eks-workshop#524]
When I try to run

```bash
wget https://eksworkshop.com/logging/deploy.files/fluentd.yml
kubectl apply -f ~/environment/fluentd/fluentd.yml
```

following instructions at https://eksworkshop.com/logging/deploy/, got this error:

```bash
error: error validating "/home/ec2-user/environment/fluentd/fluentd.yml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=falseObviously
```
fluentd.yaml file should look like this below refers to https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#pod-selector

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-cloudwatch
  namespace: kube-system
  labels:
    k8s-app: fluentd-cloudwatch
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-cloudwatch
  template:
    metadata:
      labels:
        k8s-app: fluentd-cloudwatch
...
```

, but file on 
 https://eksworkshop.com/logging/deploy.files/fluentd.yml looks not correct
