### ISSUE TITLE
unknown field "secretsEncryption"

### ISSUE THREAD

**Issue by ricoms** [aws-samples/eks-workshop#775]
`eksworkshop.yaml` is written as below at [https://eksworkshop.com/030_eksctl/launcheks/](https://eksworkshop.com/030_eksctl/launcheks/):

```
cat << EOF > eksworkshop.yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: ${AWS_REGION}

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  iam:
    withAddonPolicies:
      albIngress: true

secretsEncryption:
  keyARN: ${MASTER_ARN}
EOF
```

when running `eksctl create cluster -f eksworkshop.yaml` as required I receive the following error:
`Error: loading config file "eksworkshop.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "secretsEncryption"`
