### ISSUE TITLE
Issue with "Using AWS profiles with Kubectl config file"

### ISSUE THREAD

**Issue by hiteshjoshi1** [aws-samples/eks-workshop#816]
Trying out the section 
https://eksworkshop.com/beginner/091_iam-groups/test-cluster-access/

the following command does not work for me
```
cat $KUBECONFIG | yq w - -- 'users[*].user.exec.args[+]' '--profile' | yq w - -- 'users[*].user.exec.args[+]' 'dev' | sed 's/eksworkshop-eksctl./eksworkshop-eksctl-dev./g' | sponge $KUBECONFIG
```
It creates this snippet in the Kubeconfig inside /tmp
```
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        args:
          - token
          - -i
          - eksworkshop-eksctl
          - --profile
          - dev
```
Then when i try to create a pod
```
kubectl run --generator=run-pod/v1 nginx-dev --image=nginx -n development
```
it fails with
Flag --generator has been deprecated, has no effect and will be removed in the future.
Error: unknown flag: --profile

I think the way the Kubeconfig is modified , it is generating an invalid file. 

Related to : Allamand/using iam groups to manage 676 #757

**Comment by fmedery** [comment]
Hello,
I am unable to to reproduce the error.
Can you give me the result of:
`kubectl version --short`
`eksctl version`

**Comment by fmedery** [comment]
Do not hesitate to reopen the issue if needed.

Regard

**Comment by tigerpeng2001** [comment]
I got the same error today.
`§ kubectl get node
Error: unknown flag: --profile
Usage:
  aws-iam-authenticator token [flags]

Flags:
      --cache                  Cache the credential on disk until it expires. Uses the aws profile specified by AWS_PROFILE or the default profile.
  -e, --external-id string     External ID to pass when assuming the IAM Role
      --forward-session-name   Enable mapping a federated sessions caller-specified-role-name attribute onto newly assumed sessions. NOTE: Only applicable when a new role is requested via --role
  -h, --help                   help for token
      --region string          AWS region to use for assume role calls
  -r, --role string            Assume an IAM Role ARN before signing this token
  -s, --session-name string    Session name to pass when assuming the IAM Role
      --token-only             Return only the token for use with Bearer token based tools

Global Flags:
  -i, --cluster-id ID                 Specify the cluster ID, a unique-per-cluster identifier for your aws-iam-authenticator installation.
  -c, --config filename               Load configuration from filename
      --feature-gates mapStringBool   A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
                                      AllAlpha=true|false (ALPHA - default=false)
                                      AllBeta=true|false (BETA - default=false)
                                      IAMIdentityMappingCRD=true|false (ALPHA - default=false)
  -l, --log-format string             Specify log format to use when logging to stderr [text or json] (default "text")

Unable to connect to the server: getting credentials: exec: executable aws-iam-authenticator failed with exit code 1`

Versions
`§ kubectl version --short
Error: unknown flag: --profile
Usage:
  aws-iam-authenticator token [flags]

Flags:
      --cache                  Cache the credential on disk until it expires. Uses the aws profile specified by AWS_PROFILE or the default profile.
  -e, --external-id string     External ID to pass when assuming the IAM Role
      --forward-session-name   Enable mapping a federated sessions caller-specified-role-name attribute onto newly assumed sessions. NOTE: Only applicable when a new role is requested via --role
  -h, --help                   help for token
      --region string          AWS region to use for assume role calls
  -r, --role string            Assume an IAM Role ARN before signing this token
  -s, --session-name string    Session name to pass when assuming the IAM Role
      --token-only             Return only the token for use with Bearer token based tools

Global Flags:
  -i, --cluster-id ID                 Specify the cluster ID, a unique-per-cluster identifier for your aws-iam-authenticator installation.
  -c, --config filename               Load configuration from filename
      --feature-gates mapStringBool   A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
                                      AllAlpha=true|false (ALPHA - default=false)
                                      AllBeta=true|false (BETA - default=false)
                                      IAMIdentityMappingCRD=true|false (ALPHA - default=false)
  -l, --log-format string             Specify log format to use when logging to stderr [text or json] (default "text")

Client Version: v1.23.5
Unable to connect to the server: getting credentials: exec: executable aws-iam-authenticator failed with exit code 1
§ unset KUBECONFIG
§ kubectl version --short
Client Version: v1.23.5
Server Version: v1.22.6-eks-7d68063
§ eksctl version
0.93.0
§ aws-iam-authenticator version
{"Version":"0.5.7","Commit":"2a9ee95fecab59fab41a0b646a63227d66113434"}`

**Comment by tigerpeng2001** [comment]
After read the error message, I fixed the issue by removing the "--profile dev" from aws-iam-authenticator, and changing the env value of AWS_PROFILE from "AdminstratorRole", used to create the EKS, to "dev".

- Config segment:
```
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - token
          - -i
          - eksworkshop-eksctl
        command: aws-iam-authenticator
        env:
          - name: AWS_STS_REGIONAL_ENDPOINTS
            value: regional
          - name: AWS_DEFAULT_REGION
            value: us-east-2
          - name: AWS_PROFILE
            value: dev
        provideClusterInfo: false
```

```
§ kubectl run nginx-dev --image=nginx -n development
pod/nginx-dev created
 kubectl get pod -n development
NAME        READY   STATUS    RESTARTS   AGE
nginx-dev   1/1     Running   0          4m13s
